# Tomcat
server:
  port: 18080

# Spring
spring:
  #  LOWER_CAMEL_CASE    userName    默认策略
  #  KEBAB_CASE    user-name
  #  LOWER_CASE    username
  #  SNAKE_CASE    user_name
  #  UPPER_CAMEL_CASE    UserName
　jackson:
  　property-naming-strategy: LOWER_CAMEL_CASE
  application:
    # 应用名称
    name: demo-gateway
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        # 配置文件格式
        file-extension: yml
        # 共享配置
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/server_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: '00000000'
    initial-size: 10
    max-active: 100
    min-idle: 30
    max-wait: 40
    validation-query: SELECT 1
    druid:
      # MySql、PostgreSQL、SqlServer、DaMeng校验
      validation-query: select 1
    # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
    redis:
      host: 127.0.0.1 # 地址
      port: 6379 # 端口
      database: 11 # 数据库索引
      password: '000000'
      pool:
        maxTotal: 1000
        maxIdle: 10000

#    sentinel:
#      # 取消控制台懒加载
#      eager: true
#      transport:
#        # 控制台地址
#        dashboard: 127.0.0.1:8718
#      # nacos配置持久化
#      datasource:
#        ds1:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: demo-gateway
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: gw-flow
